In [6]:
import pandas as pd

# Series -> pandas series is a one dimentional array like object that can hold any data type

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
# create a series from dictionary 
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [9]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [11]:
# Dataframe
# Creating a dataframe from a dictionary of list

data = {
    'Name':['Rohan', 'Raghav', 'Raj'],
    'Age':[25,30,45],
    'City':['Mumbai', 'Pune', 'Banglore']
}

df = pd.DataFrame(data)

In [12]:
df

     Name  Age      City
0   Rohan   25    Mumbai
1  Raghav   30      Pune
2     Raj   45  Banglore

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
# Creating a dataframe from a list of dictionaries
data = [
    {'Name': 'Rohan', 'Age': 25,'City': 'Mumbai'},
    {'Name': 'Raghav', 'Age': 30,'City': 'Pune'},
    {'Name': 'Raj', 'Age': 45,'City': 'Banglore'}
]

In [15]:
df = pd.DataFrame(data)

In [17]:
print(df)
print(type(df))

     Name  Age      City
0   Rohan   25    Mumbai
1  Raghav   30      Pune
2     Raj   45  Banglore
<class 'pandas.core.frame.DataFrame'>

In [21]:
df = pd.read_csv('Pokemon.csv')
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [22]:
df.tail()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [23]:
# Accesing data from data frame

data = {
    'Name':['Rohan', 'Raghav', 'Raj'],
    'Age':[25,30,45],
    'City':['Mumbai', 'Pune', 'Banglore']
}

df = pd.DataFrame(data)

In [26]:
df['Name']

0     Rohan
1    Raghav
2       Raj
Name: Name, dtype: object

In [ ]:
type(df['Name']) # Dealing with columns

pandas.core.series.Series

In [ ]:
df.loc[0] # Dealing with row

Name     Rohan
Age         25
City    Mumbai
Name: 0, dtype: object

In [31]:
df.index = ['a', 'b', 'c']

In [32]:
df

     Name  Age      City
a   Rohan   25    Mumbai
b  Raghav   30      Pune
c     Raj   45  Banglore

In [34]:
df.loc['a']

Name     Rohan
Age         25
City    Mumbai
Name: a, dtype: object

In [35]:
df.iloc[0]

Name     Rohan
Age         25
City    Mumbai
Name: a, dtype: object

In [37]:
df.iloc[0, 0] # same like we do with 2D array's for getting a sigle element

'Rohan'

In [38]:
# Accessing specified element : 
df['Name']

a     Rohan
b    Raghav
c       Raj
Name: Name, dtype: object

In [42]:
df.at['b', 'Age']

np.int64(30)

In [44]:
df.at['a', 'Age']

np.int64(25)

In [45]:
#Accessing specified element using iat
df.iat[2,2]

'Banglore'

In [46]:
df.iat[0,0]

'Rohan'

In [47]:
# Data manupulation with dataframes
df

     Name  Age      City
a   Rohan   25    Mumbai
b  Raghav   30      Pune
c     Raj   45  Banglore

In [53]:
df.columns = {'Name':'Rajesh', 'Age': 27, 'City': 'Chennai'}

In [54]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [56]:
df['Salary'] = [20000, 50000, 60000]

In [57]:
df

     Name  Age      City  Salary
a   Rohan   25    Mumbai   20000
b  Raghav   30      Pune   50000
c     Raj   45  Banglore   60000

In [ ]:
df.drop('Salary', axis=1) # axis 1 works horizontally , axis 0 works vertically

     Name  Age      City
a   Rohan   25    Mumbai
b  Raghav   30      Pune
c     Raj   45  Banglore

In [61]:
df

     Name  Age      City  Salary
a   Rohan   25    Mumbai   20000
b  Raghav   30      Pune   50000
c     Raj   45  Banglore   60000

In [62]:
df.drop('Salary', axis=1, inplace=True)

In [63]:
df

     Name  Age      City
a   Rohan   25    Mumbai
b  Raghav   30      Pune
c     Raj   45  Banglore

In [65]:
# Add age to the column
df['Age'] = df['Age'] + 1

In [66]:
df

     Name  Age      City
a   Rohan   26    Mumbai
b  Raghav   31      Pune
c     Raj   46  Banglore

In [71]:
df.drop('a')

     Name  Age      City
b  Raghav   31      Pune
c     Raj   46  Banglore

In [72]:
df

     Name  Age      City
a   Rohan   26    Mumbai
b  Raghav   31      Pune
c     Raj   46  Banglore

In [73]:
df.drop('a', inplace=True)

In [74]:
df

     Name  Age      City
b  Raghav   31      Pune
c     Raj   46  Banglore

In [75]:
df = pd.read_csv('Pokemon.csv')

In [76]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [77]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000